package com.alkemy.ong.domain.model;


import com.alkemy.ong.domain.model.audit.Audit;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.Where;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Table(name = "contacts")
@ToString
@Getter
@Setter
@NoArgsConstructor
@SQLDelete(sql = "UPDATE contacts SET is_active=false where contact_id=?")
@Where(clause = "is_active=true")
public class Contact {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "contact_id")
    private Long contactId;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String phone;

    private String message;

    @Embedded
    private Audit auditable;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

}
